/*
 * registers.c
 *
 *  Created on: 15 Apr. 2025
 *      Author: lucas
 */

#include "driverlib.h"
#include "device.h"
#include "registers.h"
#include "led_driver.h"
#include <string.h>
#include <stdlib.h>

#pragma DATA_SECTION(registers, "CPU2TOCPU1RAM")
volatile float registers[TOTAL_REGISTERS];

#pragma DATA_SECTION(ipcMsg, "CPU2TOCPU1RAM")
volatile struct { uint16_t regAddr; float value; } ipcMsg;

#pragma DATA_SECTION(calibrationData, "CPU2TOCPU1RAM")
volatile BTS_channelCalibration calibrationData[NUM_CHANNELS];

#pragma DATA_SECTION(canData, "CPU1TOCPU2RAM")
volatile CAN_data canData[NUM_CHANNELS];

#pragma DATA_SECTION(startup_mode, "CPU1TOCPU2RAM")
volatile uint32_t startup_mode;

#pragma DATA_SECTION(startup_enable, "CPU1TOCPU2RAM")
volatile uint32_t startup_enable;

const RegisterConfig regConfig[TOTAL_REGISTERS] = {
    // Channel 0
    {eCh0_Mode, REG_ACCESS_RW, 4}, {eCh0_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh0_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh0_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh0_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh0_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh0_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh0_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh0_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh0_Status, REG_ACCESS_RO, 4},
    // Channel 1
    {eCh1_Mode, REG_ACCESS_RW, 4}, {eCh1_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh1_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh1_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh1_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh1_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh1_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh1_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh1_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh1_Status, REG_ACCESS_RO, 4},
    // Channel 2
    {eCh2_Mode, REG_ACCESS_RW, 4}, {eCh2_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh2_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh2_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh2_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh2_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh2_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh2_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh2_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh2_Status, REG_ACCESS_RO, 4},
    // Channel 3
    {eCh3_Mode, REG_ACCESS_RW, 4}, {eCh3_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh3_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh3_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh3_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh3_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh3_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh3_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh3_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh3_Status, REG_ACCESS_RO, 4},
    // Channel 4
    {eCh4_Mode, REG_ACCESS_RW, 4}, {eCh4_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh4_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh4_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh4_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh4_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh4_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh4_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh4_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh4_Status, REG_ACCESS_RO, 4},
    // Channel 5
    {eCh5_Mode, REG_ACCESS_RW, 4}, {eCh5_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh5_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh5_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh5_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh5_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh5_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh5_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh5_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh5_Status, REG_ACCESS_RO, 4},
    // Channel 6
    {eCh6_Mode, REG_ACCESS_RW, 4}, {eCh6_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh6_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh6_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh6_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh6_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh6_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh6_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh6_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh6_Status, REG_ACCESS_RO, 4},
    // Channel 7
    {eCh7_Mode, REG_ACCESS_RW, 4}, {eCh7_ChargeVoltageMin, REG_ACCESS_RW, 4}, {eCh7_ChargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh7_DischargeVoltageMin, REG_ACCESS_RW, 4}, {eCh7_DischargeVoltageMax, REG_ACCESS_RW, 4},
    {eCh7_ChargeCurrentMin, REG_ACCESS_RW, 4}, {eCh7_ChargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh7_DischargeCurrentMin, REG_ACCESS_RW, 4}, {eCh7_DischargeCurrentMax, REG_ACCESS_RW, 4},
    {eCh7_Status, REG_ACCESS_RO, 4},
    // Stats Block
    {eCh0_CurrentAcc, REG_ACCESS_RO, 4}, {eCh0_MinVoltage, REG_ACCESS_RO, 4}, {eCh0_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh0_PowerAcc, REG_ACCESS_RO, 4},
    {eCh1_CurrentAcc, REG_ACCESS_RO, 4}, {eCh1_MinVoltage, REG_ACCESS_RO, 4}, {eCh1_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh1_PowerAcc, REG_ACCESS_RO, 4},
    {eCh2_CurrentAcc, REG_ACCESS_RO, 4}, {eCh2_MinVoltage, REG_ACCESS_RO, 4}, {eCh2_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh2_PowerAcc, REG_ACCESS_RO, 4},
    {eCh3_CurrentAcc, REG_ACCESS_RO, 4}, {eCh3_MinVoltage, REG_ACCESS_RO, 4}, {eCh3_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh3_PowerAcc, REG_ACCESS_RO, 4},
    {eCh4_CurrentAcc, REG_ACCESS_RO, 4}, {eCh4_MinVoltage, REG_ACCESS_RO, 4}, {eCh4_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh4_PowerAcc, REG_ACCESS_RO, 4},
    {eCh5_CurrentAcc, REG_ACCESS_RO, 4}, {eCh5_MinVoltage, REG_ACCESS_RO, 4}, {eCh5_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh5_PowerAcc, REG_ACCESS_RO, 4},
    {eCh6_CurrentAcc, REG_ACCESS_RO, 4}, {eCh6_MinVoltage, REG_ACCESS_RO, 4}, {eCh6_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh6_PowerAcc, REG_ACCESS_RO, 4},
    {eCh7_CurrentAcc, REG_ACCESS_RO, 4}, {eCh7_MinVoltage, REG_ACCESS_RO, 4}, {eCh7_MaxVoltage, REG_ACCESS_RO, 4},
    {eCh7_PowerAcc, REG_ACCESS_RO, 4},
    // Calibration Block
    {eCh0_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh0_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh0_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh0_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh0_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh0_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh0_VoutGain_V, REG_ACCESS_RW, 4}, {eCh0_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCh1_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh1_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh1_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh1_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh1_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh1_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh1_VoutGain_V, REG_ACCESS_RW, 4}, {eCh1_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCh2_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh2_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh2_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh2_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh2_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh2_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh2_VoutGain_V, REG_ACCESS_RW, 4}, {eCh2_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCh3_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh3_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh3_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh3_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh3_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh3_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh3_VoutGain_V, REG_ACCESS_RW, 4}, {eCh3_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCh4_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh4_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh4_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh4_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh4_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh4_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh4_VoutGain_V, REG_ACCESS_RW, 4}, {eCh4_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCh5_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh5_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh5_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh5_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh5_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh5_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh5_VoutGain_V, REG_ACCESS_RW, 4}, {eCh5_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCh6_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh6_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh6_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh6_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh6_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh6_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh6_VoutGain_V, REG_ACCESS_RW, 4}, {eCh6_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCh7_IoutGain_pu, REG_ACCESS_RW, 4}, {eCh7_IoutOffset_pu, REG_ACCESS_RW, 4}, {eCh7_IoutGain_A, REG_ACCESS_RW, 4},
    {eCh7_IoutOffset_A, REG_ACCESS_RW, 4}, {eCh7_VoutGain_pu, REG_ACCESS_RW, 4}, {eCh7_VoutOffset_pu, REG_ACCESS_RW, 4},
    {eCh7_VoutGain_V, REG_ACCESS_RW, 4}, {eCh7_VoutOffset_V, REG_ACCESS_RW, 4},
    {eCalibrationMode, REG_ACCESS_RW, 4}
};

const UARTRegisterConfig uartRegConfig[TOTAL_REGISTERS] = {
    // Channel 0
    {eCh0_Mode, "C0M", "Ch0_Mode", REG_ACCESS_RW},
    {eCh0_ChargeVoltageMin, "C0CVMIN", "Ch0_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh0_ChargeVoltageMax, "C0CVMAX", "Ch0_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh0_DischargeVoltageMin, "C0DVMIN", "Ch0_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh0_DischargeVoltageMax, "C0DVMAX", "Ch0_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh0_ChargeCurrentMin, "C0CCMIN", "Ch0_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh0_ChargeCurrentMax, "C0CCMAX", "Ch0_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh0_DischargeCurrentMin, "C0DCMIN", "Ch0_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh0_DischargeCurrentMax, "C0DCMAX", "Ch0_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh0_Status, "C0S", "Ch0_Status", REG_ACCESS_RO},
    // Channel 1
    {eCh1_Mode, "C1M", "Ch1_Mode", REG_ACCESS_RW},
    {eCh1_ChargeVoltageMin, "C1CVMIN", "Ch1_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh1_ChargeVoltageMax, "C1CVMAX", "Ch1_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh1_DischargeVoltageMin, "C1DVMIN", "Ch1_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh1_DischargeVoltageMax, "C1DVMAX", "Ch1_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh1_ChargeCurrentMin, "C1CCMIN", "Ch1_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh1_ChargeCurrentMax, "C1CCMAX", "Ch1_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh1_DischargeCurrentMin, "C1DCMIN", "Ch1_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh1_DischargeCurrentMax, "C1DCMAX", "Ch1_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh1_Status, "C1S", "Ch1_Status", REG_ACCESS_RO},
    // Channel 2
    {eCh2_Mode, "C2M", "Ch2_Mode", REG_ACCESS_RW},
    {eCh2_ChargeVoltageMin, "C2CVMIN", "Ch2_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh2_ChargeVoltageMax, "C2CVMAX", "Ch2_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh2_DischargeVoltageMin, "C2DVMIN", "Ch2_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh2_DischargeVoltageMax, "C2DVMAX", "Ch2_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh2_ChargeCurrentMin, "C2CCMIN", "Ch2_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh2_ChargeCurrentMax, "C2CCMAX", "Ch2_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh2_DischargeCurrentMin, "C2DCMIN", "Ch2_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh2_DischargeCurrentMax, "C2DCMAX", "Ch2_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh2_Status, "C2S", "Ch2_Status", REG_ACCESS_RO},
    // Channel 3
    {eCh3_Mode, "C3M", "Ch3_Mode", REG_ACCESS_RW},
    {eCh3_ChargeVoltageMin, "C3CVMIN", "Ch3_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh3_ChargeVoltageMax, "C3CVMAX", "Ch3_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh3_DischargeVoltageMin, "C3DVMIN", "Ch3_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh3_DischargeVoltageMax, "C3DVMAX", "Ch3_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh3_ChargeCurrentMin, "C3CCMIN", "Ch3_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh3_ChargeCurrentMax, "C3CCMAX", "Ch3_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh3_DischargeCurrentMin, "C3DCMIN", "Ch3_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh3_DischargeCurrentMax, "C3DCMAX", "Ch3_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh3_Status, "C3S", "Ch3_Status", REG_ACCESS_RO},
    // Channel 4
    {eCh4_Mode, "C4M", "Ch4_Mode", REG_ACCESS_RW},
    {eCh4_ChargeVoltageMin, "C4CVMIN", "Ch4_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh4_ChargeVoltageMax, "C4CVMAX", "Ch4_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh4_DischargeVoltageMin, "C4DVMIN", "Ch4_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh4_DischargeVoltageMax, "C4DVMAX", "Ch4_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh4_ChargeCurrentMin, "C4CCMIN", "Ch4_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh4_ChargeCurrentMax, "C4CCMAX", "Ch4_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh4_DischargeCurrentMin, "C4DCMIN", "Ch4_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh4_DischargeCurrentMax, "C4DCMAX", "Ch4_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh4_Status, "C4S", "Ch4_Status", REG_ACCESS_RO},
    // Channel 5
    {eCh5_Mode, "C5M", "Ch5_Mode", REG_ACCESS_RW},
    {eCh5_ChargeVoltageMin, "C5CVMIN", "Ch5_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh5_ChargeVoltageMax, "C5CVMAX", "Ch5_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh5_DischargeVoltageMin, "C5DVMIN", "Ch5_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh5_DischargeVoltageMax, "C5DVMAX", "Ch5_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh5_ChargeCurrentMin, "C5CCMIN", "Ch5_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh5_ChargeCurrentMax, "C5CCMAX", "Ch5_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh5_DischargeCurrentMin, "C5DCMIN", "Ch5_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh5_DischargeCurrentMax, "C5DCMAX", "Ch5_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh5_Status, "C5S", "Ch5_Status", REG_ACCESS_RO},
    // Channel 6
    {eCh6_Mode, "C6M", "Ch6_Mode", REG_ACCESS_RW},
    {eCh6_ChargeVoltageMin, "C6CVMIN", "Ch6_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh6_ChargeVoltageMax, "C6CVMAX", "Ch6_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh6_DischargeVoltageMin, "C6DVMIN", "Ch6_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh6_DischargeVoltageMax, "C6DVMAX", "Ch6_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh6_ChargeCurrentMin, "C6CCMIN", "Ch6_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh6_ChargeCurrentMax, "C6CCMAX", "Ch6_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh6_DischargeCurrentMin, "C6DCMIN", "Ch6_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh6_DischargeCurrentMax, "C6DCMAX", "Ch6_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh6_Status, "C6S", "Ch6_Status", REG_ACCESS_RO},
    // Channel 7
    {eCh7_Mode, "C7M", "Ch7_Mode", REG_ACCESS_RW},
    {eCh7_ChargeVoltageMin, "C7CVMIN", "Ch7_ChargeVoltageMin", REG_ACCESS_RW},
    {eCh7_ChargeVoltageMax, "C7CVMAX", "Ch7_ChargeVoltageMax", REG_ACCESS_RW},
    {eCh7_DischargeVoltageMin, "C7DVMIN", "Ch7_DischargeVoltageMin", REG_ACCESS_RW},
    {eCh7_DischargeVoltageMax, "C7DVMAX", "Ch7_DischargeVoltageMax", REG_ACCESS_RW},
    {eCh7_ChargeCurrentMin, "C7CCMIN", "Ch7_ChargeCurrentMin", REG_ACCESS_RW},
    {eCh7_ChargeCurrentMax, "C7CCMAX", "Ch7_ChargeCurrentMax", REG_ACCESS_RW},
    {eCh7_DischargeCurrentMin, "C7DCMIN", "Ch7_DischargeCurrentMin", REG_ACCESS_RW},
    {eCh7_DischargeCurrentMax, "C7DCMAX", "Ch7_DischargeCurrentMax", REG_ACCESS_RW},
    {eCh7_Status, "C7S", "Ch7_Status", REG_ACCESS_RO},
    // Stats Block
    {eCh0_CurrentAcc, "C0CA", "Ch0_CurrentAcc", REG_ACCESS_RO},
    {eCh0_MinVoltage, "C0MINV", "Ch0_MinVoltage", REG_ACCESS_RO},
    {eCh0_MaxVoltage, "C0MAXV", "Ch0_MaxVoltage", REG_ACCESS_RO},
    {eCh0_PowerAcc, "C0PA", "Ch0_PowerAcc", REG_ACCESS_RO},
    {eCh1_CurrentAcc, "C1CA", "Ch1_CurrentAcc", REG_ACCESS_RO},
    {eCh1_MinVoltage, "C1MINV", "Ch1_MinVoltage", REG_ACCESS_RO},
    {eCh1_MaxVoltage, "C1MAXV", "Ch1_MaxVoltage", REG_ACCESS_RO},
    {eCh1_PowerAcc, "C1PA", "Ch1_PowerAcc", REG_ACCESS_RO},
    {eCh2_CurrentAcc, "C2CA", "Ch2_CurrentAcc", REG_ACCESS_RO},
    {eCh2_MinVoltage, "C2MINV", "Ch2_MinVoltage", REG_ACCESS_RO},
    {eCh2_MaxVoltage, "C2MAXV", "Ch2_MaxVoltage", REG_ACCESS_RO},
    {eCh2_PowerAcc, "C2PA", "Ch2_PowerAcc", REG_ACCESS_RO},
    {eCh3_CurrentAcc, "C3CA", "Ch3_CurrentAcc", REG_ACCESS_RO},
    {eCh3_MinVoltage, "C3MINV", "Ch3_MinVoltage", REG_ACCESS_RO},
    {eCh3_MaxVoltage, "C3MAXV", "Ch3_MaxVoltage", REG_ACCESS_RO},
    {eCh3_PowerAcc, "C3PA", "Ch3_PowerAcc", REG_ACCESS_RO},
    {eCh4_CurrentAcc, "C4CA", "Ch4_CurrentAcc", REG_ACCESS_RO},
    {eCh4_MinVoltage, "C4MINV", "Ch4_MinVoltage", REG_ACCESS_RO},
    {eCh4_MaxVoltage, "C4MAXV", "Ch4_MaxVoltage", REG_ACCESS_RO},
    {eCh4_PowerAcc, "C4PA", "Ch4_PowerAcc", REG_ACCESS_RO},
    {eCh5_CurrentAcc, "C5CA", "Ch5_CurrentAcc", REG_ACCESS_RO},
    {eCh5_MinVoltage, "C5MINV", "Ch5_MinVoltage", REG_ACCESS_RO},
    {eCh5_MaxVoltage, "C5MAXV", "Ch5_MaxVoltage", REG_ACCESS_RO},
    {eCh5_PowerAcc, "C5PA", "Ch5_PowerAcc", REG_ACCESS_RO},
    {eCh6_CurrentAcc, "C6CA", "Ch6_CurrentAcc", REG_ACCESS_RO},
    {eCh6_MinVoltage, "C6MINV", "Ch6_MinVoltage", REG_ACCESS_RO},
    {eCh6_MaxVoltage, "C6MAXV", "Ch6_MaxVoltage", REG_ACCESS_RO},
    {eCh6_PowerAcc, "C6PA", "Ch6_PowerAcc", REG_ACCESS_RO},
    {eCh7_CurrentAcc, "C7CA", "Ch7_CurrentAcc", REG_ACCESS_RO},
    {eCh7_MinVoltage, "C7MINV", "Ch7_MinVoltage", REG_ACCESS_RO},
    {eCh7_MaxVoltage, "C7MAXV", "Ch7_MaxVoltage", REG_ACCESS_RO},
    {eCh7_PowerAcc, "C7PA", "Ch7_PowerAcc", REG_ACCESS_RO},
    // Calibration Block
    {eCh0_IoutGain_pu, "C0IGPU", "UserCalibrationCh0_IoutGain_pu", REG_ACCESS_RW},
    {eCh0_IoutOffset_pu, "C0IOPU", "UserCalibrationCh0_IoutOffset_pu", REG_ACCESS_RW},
    {eCh0_IoutGain_A, "C0IGA", "UserCalibrationCh0_IoutGain_A", REG_ACCESS_RW},
    {eCh0_IoutOffset_A, "C0IOA", "UserCalibrationCh0_IoutOffset_A", REG_ACCESS_RW},
    {eCh0_VoutGain_pu, "C0VGPU", "UserCalibrationCh0_VoutGain_pu", REG_ACCESS_RW},
    {eCh0_VoutOffset_pu, "C0VOPU", "UserCalibrationCh0_VoutOffset_pu", REG_ACCESS_RW},
    {eCh0_VoutGain_V, "C0VGV", "UserCalibrationCh0_VoutGain_V", REG_ACCESS_RW},
    {eCh0_VoutOffset_V, "C0VOV", "UserCalibrationCh0_VoutOffset_V", REG_ACCESS_RW},
    {eCh1_IoutGain_pu, "C1IGPU", "UserCalibrationCh1_IoutGain_pu", REG_ACCESS_RW},
    {eCh1_IoutOffset_pu, "C1IOPU", "UserCalibrationCh1_IoutOffset_pu", REG_ACCESS_RW},
    {eCh1_IoutGain_A, "C1IGA", "UserCalibrationCh1_IoutGain_A", REG_ACCESS_RW},
    {eCh1_IoutOffset_A, "C1IOA", "UserCalibrationCh1_IoutOffset_A", REG_ACCESS_RW},
    {eCh1_VoutGain_pu, "C1VGPU", "UserCalibrationCh1_VoutGain_pu", REG_ACCESS_RW},
    {eCh1_VoutOffset_pu, "C1VOPU", "UserCalibrationCh1_VoutOffset_pu", REG_ACCESS_RW},
    {eCh1_VoutGain_V, "C1VGV", "UserCalibrationCh1_VoutGain_V", REG_ACCESS_RW},
    {eCh1_VoutOffset_V, "C1VOV", "UserCalibrationCh1_VoutOffset_V", REG_ACCESS_RW},
    {eCh2_IoutGain_pu, "C2IGPU", "UserCalibrationCh2_IoutGain_pu", REG_ACCESS_RW},
    {eCh2_IoutOffset_pu, "C2IOPU", "UserCalibrationCh2_IoutOffset_pu", REG_ACCESS_RW},
    {eCh2_IoutGain_A, "C2IGA", "UserCalibrationCh2_IoutGain_A", REG_ACCESS_RW},
    {eCh2_IoutOffset_A, "C2IOA", "UserCalibrationCh2_IoutOffset_A", REG_ACCESS_RW},
    {eCh2_VoutGain_pu, "C2VGPU", "UserCalibrationCh2_VoutGain_pu", REG_ACCESS_RW},
    {eCh2_VoutOffset_pu, "C2VOPU", "UserCalibrationCh2_VoutOffset_pu", REG_ACCESS_RW},
    {eCh2_VoutGain_V, "C2VGV", "UserCalibrationCh2_VoutGain_V", REG_ACCESS_RW},
    {eCh2_VoutOffset_V, "C2VOV", "UserCalibrationCh2_VoutOffset_V", REG_ACCESS_RW},
    {eCh3_IoutGain_pu, "C3IGPU", "UserCalibrationCh3_IoutGain_pu", REG_ACCESS_RW},
    {eCh3_IoutOffset_pu, "C3IOPU", "UserCalibrationCh3_IoutOffset_pu", REG_ACCESS_RW},
    {eCh3_IoutGain_A, "C3IGA", "UserCalibrationCh3_IoutGain_A", REG_ACCESS_RW},
    {eCh3_IoutOffset_A, "C3IOA", "UserCalibrationCh3_IoutOffset_A", REG_ACCESS_RW},
    {eCh3_VoutGain_pu, "C3VGPU", "UserCalibrationCh3_VoutGain_pu", REG_ACCESS_RW},
    {eCh3_VoutOffset_pu, "C3VOPU", "UserCalibrationCh3_VoutOffset_pu", REG_ACCESS_RW},
    {eCh3_VoutGain_V, "C3VGV", "UserCalibrationCh3_VoutGain_V", REG_ACCESS_RW},
    {eCh3_VoutOffset_V, "C3VOV", "UserCalibrationCh3_VoutOffset_V", REG_ACCESS_RW},
    {eCh4_IoutGain_pu, "C4IGPU", "UserCalibrationCh4_IoutGain_pu", REG_ACCESS_RW},
    {eCh4_IoutOffset_pu, "C4IOPU", "UserCalibrationCh4_IoutOffset_pu", REG_ACCESS_RW},
    {eCh4_IoutGain_A, "C4IGA", "UserCalibrationCh4_IoutGain_A", REG_ACCESS_RW},
    {eCh4_IoutOffset_A, "C4IOA", "UserCalibrationCh4_IoutOffset_A", REG_ACCESS_RW},
    {eCh4_VoutGain_pu, "C4VGPU", "UserCalibrationCh4_VoutGain_pu", REG_ACCESS_RW},
    {eCh4_VoutOffset_pu, "C4VOPU", "UserCalibrationCh4_VoutOffset_pu", REG_ACCESS_RW},
    {eCh4_VoutGain_V, "C4VGV", "UserCalibrationCh4_VoutGain_V", REG_ACCESS_RW},
    {eCh4_VoutOffset_V, "C4VOV", "UserCalibrationCh4_VoutOffset_V", REG_ACCESS_RW},
    {eCh5_IoutGain_pu, "C5IGPU", "UserCalibrationCh5_IoutGain_pu", REG_ACCESS_RW},
    {eCh5_IoutOffset_pu, "C5IOPU", "UserCalibrationCh5_IoutOffset_pu", REG_ACCESS_RW},
    {eCh5_IoutGain_A, "C5IGA", "UserCalibrationCh5_IoutGain_A", REG_ACCESS_RW},
    {eCh5_IoutOffset_A, "C5IOA", "UserCalibrationCh5_IoutOffset_A", REG_ACCESS_RW},
    {eCh5_VoutGain_pu, "C5VGPU", "UserCalibrationCh5_VoutGain_pu", REG_ACCESS_RW},
    {eCh5_VoutOffset_pu, "C5VOPU", "UserCalibrationCh5_VoutOffset_pu", REG_ACCESS_RW},
    {eCh5_VoutGain_V, "C5VGV", "UserCalibrationCh5_VoutGain_V", REG_ACCESS_RW},
    {eCh5_VoutOffset_V, "C5VOV", "UserCalibrationCh5_VoutOffset_V", REG_ACCESS_RW},
    {eCh6_IoutGain_pu, "C6IGPU", "UserCalibrationCh6_IoutGain_pu", REG_ACCESS_RW},
    {eCh6_IoutOffset_pu, "C6IOPU", "UserCalibrationCh6_IoutOffset_pu", REG_ACCESS_RW},
    {eCh6_IoutGain_A, "C6IGA", "UserCalibrationCh6_IoutGain_A", REG_ACCESS_RW},
    {eCh6_IoutOffset_A, "C6IOA", "UserCalibrationCh6_IoutOffset_A", REG_ACCESS_RW},
    {eCh6_VoutGain_pu, "C6VGPU", "UserCalibrationCh6_VoutGain_pu", REG_ACCESS_RW},
    {eCh6_VoutOffset_pu, "C6VOPU", "UserCalibrationCh6_VoutOffset_pu", REG_ACCESS_RW},
    {eCh6_VoutGain_V, "C6VGV", "UserCalibrationCh6_VoutGain_V", REG_ACCESS_RW},
    {eCh6_VoutOffset_V, "C6VOV", "UserCalibrationCh6_VoutOffset_V", REG_ACCESS_RW},
    {eCh7_IoutGain_pu, "C7IGPU", "UserCalibrationCh7_IoutGain_pu", REG_ACCESS_RW},
    {eCh7_IoutOffset_pu, "C7IOPU", "UserCalibrationCh7_IoutOffset_pu", REG_ACCESS_RW},
    {eCh7_IoutGain_A, "C7IGA", "UserCalibrationCh7_IoutGain_A", REG_ACCESS_RW},
    {eCh7_IoutOffset_A, "C7IOA", "UserCalibrationCh7_IoutOffset_A", REG_ACCESS_RW},
    {eCh7_VoutGain_pu, "C7VGPU", "UserCalibrationCh7_VoutGain_pu", REG_ACCESS_RW},
    {eCh7_VoutOffset_pu, "C7VOPU", "UserCalibrationCh7_VoutOffset_pu", REG_ACCESS_RW},
    {eCh7_VoutGain_V, "C7VGV", "UserCalibrationCh7_VoutGain_V", REG_ACCESS_RW},
    {eCh7_VoutOffset_V, "C7VOV", "UserCalibrationCh7_VoutOffset_V", REG_ACCESS_RW},
    {eCalibrationMode, "CALM", "CalibrationMode", REG_ACCESS_RW}
};
