//AddWatchWindowVars Build 1
expRemoveAll()
//Variables
expAdd ("TTPLPFC_lab.enum_lab",getNatural())
expAdd ("TTPLPFC_pwm_SwState.enum_pwmSwState",getNatural())
expAdd ("TTPLPFC_vBus_sensed_Volts",getNatural())
expAdd ("TTPLPFC_ac_vol_sensed_Volts",getNatural())
expAdd ("TTPLPFC_ac_volRms_sensed_Volts",getNatural())
expAdd ("TTPLPFC_ac_curRms_sensed_Amps",getNatural())
expAdd ("TTPLPFC_ac_cur_sensed_Amps",getNatural())
expAdd ("TTPLPFC_ac_cur_senseOffset_pu",getNatural())
expAdd ("TTPLPFC_clearTrip", getNatural())
expAdd ("EPwm1Regs.TZFLG",getNatural())
expAdd ("EPwm2Regs.TZFLG",getNatural())
expAdd ("TTPLPFC_dutyPU",getNatural())
expAdd ("TTPLPFC_dutyPU_DC",getNatural())
expAdd ("TTPLPFC_vBus_sensed_Volts",getNatural())
expAdd ("TTPLPFC_iL1_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL2_sensed_pu",getNatural())
expAdd ("TTPLPFC_iL2_sensed_pu",getNatural())
expAdd ("TTPLPFC_autoStartSlew",getNatural())
