//Expressions Watch Window Variables for Lab 1 (Open Loop VMC)
expRemoveAll()
//Variables
expAdd ("BTS_userInput_ch1",getNatural())
expAdd ("BTS_ctrlLoopVariable_ch1",getNatural())
expAdd ("BTS_measValues_ch1",getNatural())
expAdd ("BTS_userInput_ch2",getNatural())
expAdd ("BTS_ctrlLoopVariable_ch2",getNatural())
expAdd ("BTS_measValues_ch2",getNatural())
expAdd ("BTS_userInput_ch3",getNatural())
expAdd ("BTS_ctrlLoopVariable_ch3",getNatural())
expAdd ("BTS_measValues_ch3",getNatural())
expAdd ("BTS_userInput_ch4",getNatural())
expAdd ("BTS_ctrlLoopVariable_ch4",getNatural())
expAdd ("BTS_measValues_ch4",getNatural())